---
install_repository_dependencies: true
install_resolver_dependencies: true
install_tool_dependencies: false

tools:
  - name: velvetoptimiser
    owner: simon-gladman
    tool_panel_section_label: Assembly
  - name: fasta_stats
    owner: simon-gladman
    tool_panel_section_label: Assembly
